[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/auth/login"
healthcheckTimeout = 300

[[volumes]]
mountPath = "/data"
